table cotacoes
	lineageTag: 6b5e41a0-1731-438b-85ad-5f14a384d1d9

	measure 'Cotação do dia' = ```
			AVERAGE(cotacoes[Cotacao]) 
			```
		displayFolder: Medidas
		lineageTag: 5d4c57f6-0a68-483c-a8b7-5a3ef375b987

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: e9780f36-561d-4668-9efb-22a53d010188
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	column DataHora
		dataType: dateTime
		formatString: General Date
		displayFolder: Colunas
		lineageTag: 63a430ba-5885-444d-be75-8128e2901d72
		summarizeBy: none
		sourceColumn: DataHora

		annotation SummarizationSetBy = Automatic

	column Cotacao
		dataType: double
		displayFolder: Colunas
		lineageTag: 76780516-0c7f-4411-9da8-d2669ffab55c
		summarizeBy: sum
		sourceColumn: Cotacao

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TipoBoletim
		dataType: string
		displayFolder: Colunas
		lineageTag: 1fcc72f6-35ca-49f0-80be-f09a1df8ce89
		summarizeBy: none
		sourceColumn: TipoBoletim

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Short Date
		displayFolder: Colunas
		lineageTag: b9dbf6a2-9e18-4405-a796-ab72edd7b929
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition cotacoes = m
		mode: import
		queryGroup: Fatos
		source = getCotacoes(data_inicial, data_final)

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

